INCLUDEPATH += \
	$$IN_PWD/modules/uuid/include \ \
	$$IN_PWD/modules/uuid/include \
	$$IN_PWD/modules/config/include \
	$$IN_PWD/modules/type_traits/include \
	$$IN_PWD/modules/mpl/include \
	$$IN_PWD/modules/preprocessor/include \
	$$IN_PWD/modules/throw_exception/include \
	$$IN_PWD/modules/assert/include \
	$$IN_PWD/modules/static_assert/include \
	$$IN_PWD/modules/core/include \
	$$IN_PWD/modules/iterator/include \
	$$IN_PWD/modules/detail/include \
	$$IN_PWD/modules/system/include \
	$$IN_PWD/modules/predef/include \
	$$IN_PWD/modules/integer/include \
	$$IN_PWD/modules/smart_ptr/include \
	$$IN_PWD/modules/random/include \
	$$IN_PWD/modules/range/include \
	$$IN_PWD/modules/concept_check/include \
	$$IN_PWD/modules/utility/include \
	$$IN_PWD/modules/io/include \
	$$IN_PWD/modules/signals2/include \
	$$IN_PWD/modules/optional/include \
	$$IN_PWD/modules/move/include \
	$$IN_PWD/modules/function/include \
	$$IN_PWD/modules/bind/include \
	$$IN_PWD/modules/variant/include \
	$$IN_PWD/modules/type_index/include \
	$$IN_PWD/modules/functional/include \
	$$IN_PWD/modules/math/include \
	$$IN_PWD/modules/multi_index/include \
	$$IN_PWD/modules/parameter/include \
	$$IN_PWD/modules/serialization/include \
	$$IN_PWD/modules/align/include

DEPENDPATH += \
	$$IN_PWD/modules/uuid/include \
	$$IN_PWD/modules/config/include \
	$$IN_PWD/modules/type_traits/include \
	$$IN_PWD/modules/mpl/include \
	$$IN_PWD/modules/preprocessor/include \
	$$IN_PWD/modules/throw_exception/include \
	$$IN_PWD/modules/assert/include \
	$$IN_PWD/modules/static_assert/include \
	$$IN_PWD/modules/core/include \
	$$IN_PWD/modules/iterator/include \
	$$IN_PWD/modules/detail/include \
	$$IN_PWD/modules/system/include \
	$$IN_PWD/modules/predef/include \
	$$IN_PWD/modules/integer/include \
	$$IN_PWD/modules/smart_ptr/include \
	$$IN_PWD/modules/random/include \
	$$IN_PWD/modules/range/include \
	$$IN_PWD/modules/concept_check/include \
	$$IN_PWD/modules/utility/include \
	$$IN_PWD/modules/io/include \
	$$IN_PWD/modules/signals2/include \
	$$IN_PWD/modules/optional/include \
	$$IN_PWD/modules/move/include \
	$$IN_PWD/modules/function/include \
	$$IN_PWD/modules/bind/include \
	$$IN_PWD/modules/variant/include \
	$$IN_PWD/modules/type_index/include \
	$$IN_PWD/modules/functional/include \
	$$IN_PWD/modules/math/include \
	$$IN_PWD/modules/multi_index/include \
	$$IN_PWD/modules/parameter/include \
	$$IN_PWD/modules/serialization/include \
	$$IN_PWD/modules/align/include
